"""Prompt template + the JSON Schema for :class:`ToolSpec`.

Pure module — no I/O, no LLM calls. Adapter tests can assert prompt
shape without mocking subprocess or the SDK.
"""

from __future__ import annotations

from typing import Any

from .introspection import SymbolMeta

TOOL_SPEC_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "description": {
            "type": "string",
            "description": (
                "WHEN-to-call focused tool description for an LLM consumer. "
                "1-3 sentences. Emphasize when to call, not just what."
            ),
        },
        "parameters": {
            "type": "object",
            "description": (
                "JSON Schema for the tool's arguments. Standard "
                '{"type": "object", "properties": {...}, "required": [...]} shape.'
            ),
        },
        "notes": {
            "type": "string",
            "description": (
                "Free-form caveats / known gotchas for the agent. "
                "May be the empty string if there is nothing to flag."
            ),
        },
    },
    "required": ["description", "parameters", "notes"],
    "additionalProperties": False,
}


PROMPT_TEMPLATE = """\
You are generating an MCP tool specification for a PsyNeuLink symbol.

The host system wraps your output into a Python module that registers a single
MCP tool. You only emit the metadata — the implementation body is generated by
a fixed template that calls `psyneulink.{short_name}` with the agent's kwargs.

Symbol:  {qualname}
Kind:    {kind}
Module:  {module}
{kind_addendum}
--- DOCSTRING ---
{docstring}

--- SOURCE ---
{source}

--- RECENT FEEDBACK ---
{feedback}

Return a ToolSpec with these fields:

- description: 1-3 sentences. WHEN should an agent call this tool? What does
  the result look like? Optimize for an LLM consumer reading the description
  while deciding which tool to call. Do NOT just restate the docstring.

- parameters: a JSON Schema describing the keyword arguments the agent should
  pass. The host instantiates `{qualname}` with these arguments (for classes)
  or calls it (for functions). Choose argument names, types, defaults, and
  required-set from the symbol's signature + docstring. Use narrow JSON Schema
  types (string, integer, number, boolean, array, object) — avoid `any`.
  Include short per-property `description` strings. The schema's outer shape
  must be an object: {{"type": "object", "properties": {{...}}, "required": [...]}}.

- notes: caveats the agent should know — silent defaults, units, dimensional
  expectations, surprising behavior, deprecations, anything in the source that
  would trip an LLM. Empty string if there is nothing to flag.

If RECENT FEEDBACK is non-empty, address it directly in the description,
parameters, or notes — that's what the feedback loop is for.

Output ONLY the structured ToolSpec; no prose, no markdown.
"""


# Extra context the LLM needs for method-kind seeds. Methods on
# PsyNeuLink classes (e.g. ``Composition.add_projection``) bind to a
# live instance at runtime; the generated tool's ``_impl`` resolves
# that instance from a ``composition`` handle kwarg. The runtime
# helper at ``psyneulink_mcp.method_helpers.call_method_tool`` also
# bakes in a few defensive behaviours that aren't in the PNL source —
# without this addendum the LLM emits descriptions that contradict the
# helper's actual semantics (e.g. "you must add nodes first" when the
# helper auto-adds them).
_METHOD_ADDENDUM_TEMPLATE = """
Method-kind contract (read carefully — this changes what you should put in
description / parameters / notes):

- The generated tool is bound to a live `{class_short_name}` instance at call
  time. The agent passes that instance as a `composition` handle string. Your
  `parameters` schema MUST list `composition` as a string property and put
  it in `required`. Describe `composition` as the handle returned by
  `create_composition` (or the analogous constructor for the bound class).

- Do NOT include the `self` / `context` parameters of the underlying Python
  method in your schema — they're managed by the runtime.

- The runtime helper (`psyneulink_mcp.method_helpers.call_method_tool`)
  resolves every PsyNeuLink-handle kwarg from string → live object before
  dispatching the call, and also resolves bare class-name strings under
  function-type keys (e.g. `function="Linear"` → `pnl.Linear`). Document
  parameters in handle-string terms.

{method_specific_addendum}
"""


_METHOD_SPECIFIC_ADDENDA: dict[str, str] = {
    "psyneulink.Composition.add_projection": (
        "- For `add_projection` SPECIFICALLY: the runtime helper "
        "DEFENSIVELY adds the sender and receiver to the composition before "
        "creating the projection (PsyNeuLink no-ops if either is already "
        "in). Captured failures showed agents trip over "
        "`CompositionError: ... not (yet) in it`; the helper now prevents "
        "those. Reflect this in the description: the agent does NOT have "
        "to call `add_node` first.\n"
        "- The helper also TREATS `DuplicateProjectionError` AS A NO-OP "
        "SUCCESS — the desired wiring already exists. Mention that "
        "retrying an `add_projection` is safe.\n"
        "- The PNL parameter is `default_matrix`, not `matrix`. Captured "
        "failures showed agents passing `matrix='IDENTITY_MATRIX'` "
        "directly to a free-standing `MappingProjection`, which trips a "
        "PNL parameter-port bug. The helper translates either kwarg name "
        "to PNL's `default_matrix` for you, but the schema you emit "
        "should advertise `default_matrix` (a 2-D numeric array OR a PNL "
        "matrix-keyword string like `IDENTITY_MATRIX`, "
        "`FULL_CONNECTIVITY_MATRIX`, `HOLLOW_MATRIX`, "
        "`RANDOM_CONNECTIVITY_MATRIX`)."
    ),
    "psyneulink.Composition.add_node": (
        "- Adding a node that is already in the Composition is a silent "
        "no-op; the agent can call this defensively without checking."
    ),
    "psyneulink.Composition.add_linear_processing_pathway": (
        "- Use this for feed-forward chains. The first PNL parameter is "
        "called `pathway` (an ordered list of node handles). Auto-created "
        "default MappingProjections wire each consecutive pair."
    ),
}


def render_prompt(symbol: SymbolMeta, feedback: list[dict] | None = None) -> str:
    """Render the user-prompt for one symbol.

    ``feedback`` is the merged list of local + corpus envelopes for
    this tool name (already grouped by ``orchestrator.gather_feedback``).
    """
    feedback_text = (
        "(none)"
        if not feedback
        else "\n".join(repr(entry) for entry in feedback)
    )
    if symbol.kind == "method":
        method_addendum = _METHOD_SPECIFIC_ADDENDA.get(symbol.qualname, "")
        kind_addendum = _METHOD_ADDENDUM_TEMPLATE.format(
            class_short_name=symbol.class_short_name or "?",
            method_specific_addendum=method_addendum,
        )
    else:
        kind_addendum = ""
    return PROMPT_TEMPLATE.format(
        qualname=symbol.qualname,
        short_name=symbol.short_name,
        kind=symbol.kind,
        module=symbol.module,
        kind_addendum=kind_addendum,
        docstring=symbol.docstring or "(no docstring)",
        source=symbol.source,
        feedback=feedback_text,
    )
