"""Prompt template + the JSON Schema for :class:`ToolSpec`.

Pure module — no I/O, no LLM calls. Adapter tests can assert prompt
shape without mocking subprocess or the SDK.
"""

from __future__ import annotations

from typing import Any

from .introspection import SymbolMeta

TOOL_SPEC_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "description": {
            "type": "string",
            "description": (
                "WHEN-to-call focused tool description for an LLM consumer. "
                "1-3 sentences. Emphasize when to call, not just what."
            ),
        },
        "parameters": {
            "type": "object",
            "description": (
                "JSON Schema for the tool's arguments. Standard "
                '{"type": "object", "properties": {...}, "required": [...]} shape.'
            ),
        },
        "notes": {
            "type": "string",
            "description": (
                "Free-form caveats / known gotchas for the agent. "
                "May be the empty string if there is nothing to flag."
            ),
        },
    },
    "required": ["description", "parameters", "notes"],
    "additionalProperties": False,
}


PROMPT_TEMPLATE = """\
You are generating an MCP tool specification for a PsyNeuLink symbol.

The host system wraps your output into a Python module that registers a single
MCP tool. You only emit the metadata — the implementation body is generated by
a fixed template that calls `psyneulink.{short_name}` with the agent's kwargs.

Symbol:  {qualname}
Kind:    {kind}
Module:  {module}
{kind_addendum}
--- DOCSTRING ---
{docstring}
{parents_section}{examples_section}
--- SOURCE ---
{source}

--- RECENT FEEDBACK ---
{feedback}

Return a ToolSpec with these fields:

- description: 1-3 sentences. WHEN should an agent call this tool? What does
  the result look like? Optimize for an LLM consumer reading the description
  while deciding which tool to call. Do NOT just restate the docstring.{compression_clause}

- parameters: a JSON Schema describing the keyword arguments the agent should
  pass. The host instantiates `{qualname}` with these arguments (for classes)
  or calls it (for functions). Choose argument names, types, defaults, and
  required-set from the symbol's signature + docstring. Use narrow JSON Schema
  types (string, integer, number, boolean, array, object) — avoid `any`.
  Include short per-property `description` strings. The schema's outer shape
  must be an object: {{"type": "object", "properties": {{...}}, "required": [...]}}.

- notes: caveats the agent should know — silent defaults, units, dimensional
  expectations, surprising behavior, deprecations, anything in the source that
  would trip an LLM. Empty string if there is nothing to flag.

If RECENT FEEDBACK is non-empty, address it directly in the description,
parameters, or notes — that's what the feedback loop is for.

CRITICAL — describe THIS tool only.

Each tool's description must be self-contained and about this tool alone. Do
NOT recommend a different tool by name as an alternative or workaround. If
feedback says "the agent fixed this by using EMComposition / a pathway tool /
a different mechanism", describe what doesn't work in THIS tool — not what to
use instead. The agent decides which tool to use; your job is to describe what
each tool is and its constraints. Cross-referencing other tools by name
silently couples descriptions: when that other tool gets renamed or removed,
this description rots.

Mentioning related concepts, parameters, or PNL classes is fine ("the
returned handle goes into a Composition", "this is a subclass of Mechanism").
Mentioning other tool names by their `create_*` MCP name as recommended
substitutes is not.

Output ONLY the structured ToolSpec; no prose, no markdown.
"""


# Extra context the LLM needs for method-kind seeds. Methods on
# PsyNeuLink classes (e.g. ``Composition.add_projection``) bind to a
# live instance at runtime; the generated tool's ``_impl`` resolves
# that instance from a ``composition`` handle kwarg. The runtime
# helper at ``psyneulink_mcp.method_helpers.call_method_tool`` also
# bakes in a few defensive behaviours that aren't in the PNL source —
# without this addendum the LLM emits descriptions that contradict the
# helper's actual semantics (e.g. "you must add nodes first" when the
# helper auto-adds them).
_METHOD_ADDENDUM_TEMPLATE = """
Method-kind contract (read carefully — this changes what you should put in
description / parameters / notes):

- The generated tool is bound to a live `{class_short_name}` instance at call
  time. The agent passes that instance as a `composition` handle string. Your
  `parameters` schema MUST list `composition` as a string property and put
  it in `required`. Describe `composition` as the handle returned by
  `create_composition` (or the analogous constructor for the bound class).

- Do NOT include the `self` / `context` parameters of the underlying Python
  method in your schema — they're managed by the runtime.

- The runtime helper (`psyneulink_mcp.method_helpers.call_method_tool`)
  resolves every PsyNeuLink-handle kwarg from string → live object before
  dispatching the call, and also resolves bare class-name strings under
  function-type keys (e.g. `function="Linear"` → `pnl.Linear`). Document
  parameters in handle-string terms.

{method_specific_addendum}
"""


_METHOD_SPECIFIC_ADDENDA: dict[str, str] = {
    "psyneulink.Composition.add_projection": (
        "- For `add_projection` SPECIFICALLY: the runtime helper "
        "DEFENSIVELY adds the sender and receiver to the composition before "
        "creating the projection (PsyNeuLink no-ops if either is already "
        "in). Captured failures showed agents trip over "
        "`CompositionError: ... not (yet) in it`; the helper now prevents "
        "those. Reflect this in the description: the agent does NOT have "
        "to call `add_node` first.\n"
        "- The helper also TREATS `DuplicateProjectionError` AS A NO-OP "
        "SUCCESS — the desired wiring already exists. Mention that "
        "retrying an `add_projection` is safe.\n"
        "- The PNL parameter is `default_matrix`, not `matrix`. Captured "
        "failures showed agents passing `matrix='IDENTITY_MATRIX'` "
        "directly to a free-standing `MappingProjection`, which trips a "
        "PNL parameter-port bug. The helper translates either kwarg name "
        "to PNL's `default_matrix` for you, but the schema you emit "
        "should advertise `default_matrix` (a 2-D numeric array OR a PNL "
        "matrix-keyword string like `IDENTITY_MATRIX`, "
        "`FULL_CONNECTIVITY_MATRIX`, `HOLLOW_MATRIX`, "
        "`RANDOM_CONNECTIVITY_MATRIX`)."
    ),
    "psyneulink.Composition.add_node": (
        "- Adding a node that is already in the Composition is a silent "
        "no-op; the agent can call this defensively without checking."
    ),
    "psyneulink.Composition.add_linear_processing_pathway": (
        "- Use this for feed-forward chains. The first PNL parameter is "
        "called `pathway` (an ordered list of node handles). Auto-created "
        "default MappingProjections wire each consecutive pair."
    ),
}


_COMPRESSION_CLAUSE = (
    "\n  This class inherits from the parents listed under "
    "INHERITS FROM above. The runtime exposes that hierarchy to the "
    "agent via `describe_psyneulink_tool` (the agent can drill into "
    "any parent's tool by name), so your description should focus on "
    "what THIS class adds beyond those parents. Do NOT re-explain "
    "behavior or parameters that are documented on a parent — assume "
    "the agent will look those up. Mention parents by name when it "
    "helps clarity."
)


def _render_parents_section(symbol: SymbolMeta) -> str:
    """Render the optional ``--- INHERITS FROM ---`` block for the prompt.

    Only emitted for class-kind symbols that have at least one parent
    docstring captured at introspection time. Includes each parent's
    short name + first-paragraph docstring (already char-capped in
    introspection). Empty string when the symbol has no usable parents
    — the prompt template tolerates that without an extra newline.
    """
    if symbol.kind != "class" or not symbol.parent_docstrings:
        return ""
    lines = ["", "--- INHERITS FROM ---"]
    for parent_short, parent_doc in symbol.parent_docstrings:
        lines.append(f"## {parent_short}")
        lines.append(parent_doc)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_prompt(symbol: SymbolMeta, feedback: list[dict] | None = None) -> str:
    """Render the user-prompt for one symbol.

    ``feedback`` is the merged list of local + corpus envelopes for
    this tool name (already grouped by ``orchestrator.gather_feedback``).
    """
    feedback_text = (
        "(none)"
        if not feedback
        else "\n".join(repr(entry) for entry in feedback)
    )
    if symbol.kind == "method":
        method_addendum = _METHOD_SPECIFIC_ADDENDA.get(symbol.qualname, "")
        kind_addendum = _METHOD_ADDENDUM_TEMPLATE.format(
            class_short_name=symbol.class_short_name or "?",
            method_specific_addendum=method_addendum,
        )
    else:
        kind_addendum = ""
    parents_section = _render_parents_section(symbol)
    compression_clause = _COMPRESSION_CLAUSE if parents_section else ""
    examples_section = _render_examples_section(symbol)
    return PROMPT_TEMPLATE.format(
        qualname=symbol.qualname,
        short_name=symbol.short_name,
        kind=symbol.kind,
        module=symbol.module,
        kind_addendum=kind_addendum,
        docstring=symbol.docstring or "(no docstring)",
        source=symbol.source,
        feedback=feedback_text,
        parents_section=parents_section,
        compression_clause=compression_clause,
        examples_section=examples_section,
    )


def _render_examples_section(symbol: SymbolMeta) -> str:
    """Render the optional ``--- USAGE EXAMPLES FROM PSYNEULINK ---`` block.

    Pulls 0-2 snippets from PNL's ``library/models/`` and
    ``library/compositions/`` (canonical reproductions of published
    cognitive models). Returns the empty string when no canonical
    model uses this symbol — that's the safety valve so adding an
    example source can never break prompt rendering.

    For methods we look up the owning class's short name; the surface
    use sites for ``Composition.add_projection`` are spelled
    ``composition.add_projection(...)`` and don't word-boundary match
    the bare method name in any useful way.
    """
    from .pnl_examples import find_examples_for, render_examples_block

    if symbol.kind == "method" and symbol.class_short_name:
        needle = symbol.class_short_name
    else:
        needle = symbol.short_name
    snippets = find_examples_for(needle)
    return render_examples_block(snippets)
