"""Prompt template + the JSON Schema for :class:`ToolSpec`.

Pure module — no I/O, no LLM calls. Adapter tests can assert prompt
shape without mocking subprocess or the SDK.
"""

from __future__ import annotations

from typing import Any

from .introspection import SymbolMeta

TOOL_SPEC_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "description": {
            "type": "string",
            "description": (
                "WHEN-to-call focused tool description for an LLM consumer. "
                "1-3 sentences. Emphasize when to call, not just what."
            ),
        },
        "parameters": {
            "type": "object",
            "description": (
                "JSON Schema for the tool's arguments. Standard "
                '{"type": "object", "properties": {...}, "required": [...]} shape.'
            ),
        },
        "notes": {
            "type": "string",
            "description": (
                "Free-form caveats / known gotchas for the agent. "
                "May be the empty string if there is nothing to flag."
            ),
        },
    },
    "required": ["description", "parameters", "notes"],
    "additionalProperties": False,
}


PROMPT_TEMPLATE = """\
You are generating an MCP tool specification for a PsyNeuLink symbol.

The host system wraps your output into a Python module that registers a single
MCP tool. You only emit the metadata — the implementation body is generated by
a fixed template that calls `psyneulink.{short_name}` with the agent's kwargs.

Symbol:  {qualname}
Kind:    {kind}
Module:  {module}

--- DOCSTRING ---
{docstring}

--- SOURCE ---
{source}

--- RECENT FEEDBACK ---
{feedback}

Return a ToolSpec with these fields:

- description: 1-3 sentences. WHEN should an agent call this tool? What does
  the result look like? Optimize for an LLM consumer reading the description
  while deciding which tool to call. Do NOT just restate the docstring.

- parameters: a JSON Schema describing the keyword arguments the agent should
  pass. The host instantiates `{qualname}` with these arguments (for classes)
  or calls it (for functions). Choose argument names, types, defaults, and
  required-set from the symbol's signature + docstring. Use narrow JSON Schema
  types (string, integer, number, boolean, array, object) — avoid `any`.
  Include short per-property `description` strings. The schema's outer shape
  must be an object: {{"type": "object", "properties": {{...}}, "required": [...]}}.

- notes: caveats the agent should know — silent defaults, units, dimensional
  expectations, surprising behavior, deprecations, anything in the source that
  would trip an LLM. Empty string if there is nothing to flag.

If RECENT FEEDBACK is non-empty, address it directly in the description,
parameters, or notes — that's what the feedback loop is for.

Output ONLY the structured ToolSpec; no prose, no markdown.
"""


def render_prompt(symbol: SymbolMeta, feedback: list[dict] | None = None) -> str:
    """Render the user-prompt for one symbol.

    ``feedback`` is the merged list of local + corpus envelopes for
    this tool name (already grouped by ``orchestrator.gather_feedback``).
    """
    feedback_text = (
        "(none)"
        if not feedback
        else "\n".join(repr(entry) for entry in feedback)
    )
    return PROMPT_TEMPLATE.format(
        qualname=symbol.qualname,
        short_name=symbol.short_name,
        kind=symbol.kind,
        module=symbol.module,
        docstring=symbol.docstring or "(no docstring)",
        source=symbol.source,
        feedback=feedback_text,
    )
